@echo off
echo 🚀 Starting deployment process...

echo 📦 Generating Prisma client...
call npx prisma generate

echo 🔨 Building TypeScript...
call npm run build

echo 🗄️  Pushing database schema...
call npx prisma db push

echo 🎯 Starting application...
call npm start
